<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class UserSeederFromSheet extends Seeder
{
    public function run()
    {
        // Auto-generated from Excel: Rekap Data Pegawai.xlsx
        // Columns preserved: id, name, email, no_hp, jabatan, unit, tingkatan, password, role, hirarki, created_at, update_at
        $rawRows = [
            [
                'id' => null,
                'name' => 'Drs Pandi, S.H., M.H.',
                'email' => 'email1@gmail.com',
                'no_hp' => '0812',
                'jabatan' => 'Ketua Pengadilan Tinggi Agama Papua Barat',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Approval',
                'hirarki' => '1',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Dr. Drs. H. Moh. Faishol Hasanuddin, S.H., M.H.',
                'email' => 'email2@gmail.com',
                'no_hp' => '0813',
                'jabatan' => 'Wakil Ketua',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '2',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Drs. Muhammad Takdir, S.H., M.H.',
                'email' => 'email3@gmail.com',
                'no_hp' => '0814',
                'jabatan' => 'Hakim Tinggi',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '3',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Drs Basyirun, M.H.',
                'email' => 'email4@gmail.com',
                'no_hp' => '0815',
                'jabatan' => 'Hakim Tinggi',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '4',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Drs. Rahmat Farid, M.H.',
                'email' => 'email5@gmail.com',
                'no_hp' => '0816',
                'jabatan' => 'Hakim Tinggi',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '5',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Nurmansyah, S.Ag., M.H',
                'email' => 'email6@gmail.com',
                'no_hp' => '0817',
                'jabatan' => 'Sekretaris',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '6',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Dr. Imran, S.Ag., S.H., M.H.',
                'email' => 'email7@gmail.com',
                'no_hp' => '0818',
                'jabatan' => 'Panitera',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '7',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Khoiriyah, S.Ag., M.H.',
                'email' => 'email8@gmail.com',
                'no_hp' => '0819',
                'jabatan' => 'Panitera Muda Hukum',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '8',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Musa Sholawat, S.H.I.',
                'email' => 'email9@gmail.com',
                'no_hp' => '0820',
                'jabatan' => 'Panitera Muda Banding',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '9',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Raswin, S.H.I.',
                'email' => 'email10@gmail.com',
                'no_hp' => '0821',
                'jabatan' => 'Kepala Bagian Umum dan Keuangan',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '10',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Syamsul Bahri, S.H.I.',
                'email' => 'email11@gmail.com',
                'no_hp' => '0822',
                'jabatan' => 'Kepala Bagian Perencanaan dan Kepegawaian',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '11',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Akram, S.H., M.H.',
                'email' => 'email12@gmail.com',
                'no_hp' => '0823',
                'jabatan' => 'Panitera Pengganti',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '12',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Missah Hamzah Suara, S.H.',
                'email' => 'email13@gmail.com',
                'no_hp' => '0824',
                'jabatan' => 'Panitera Pengganti',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '13',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Manik Rochmani, S.H.',
                'email' => 'email14@gmail.com',
                'no_hp' => '0825',
                'jabatan' => 'Kepala Sub Bagian Rencana Program dan Anggaran',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '14',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Ummu Mukhlisa, S.H., M.H.',
                'email' => 'email15@gmail.com',
                'no_hp' => '0826',
                'jabatan' => 'Kepala Sub Bagian Tata Usaha dan Rumah Tangga',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '15',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Suria Kencana, S.E.',
                'email' => 'email16@gmail.com',
                'no_hp' => '0827',
                'jabatan' => 'Kepala Sub Bagian Keuangan dan Pelaporan',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '16',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Muslim Amin, A.Md.A.B.',
                'email' => 'email17@gmail.com',
                'no_hp' => '0828',
                'jabatan' => 'Arsiparis Terampil',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '17',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Sitti Suriyani Tuahuns, S.Pd.Sd',
                'email' => 'email18@gmail.com',
                'no_hp' => '0829',
                'jabatan' => 'Pengadministrasi Perkantoran',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '18',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Ahmad Nur Fajri, S.H.',
                'email' => 'email19@gmail.com',
                'no_hp' => '0830',
                'jabatan' => 'Analis Perkara Peradilan',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '19',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Akbar, S.H.',
                'email' => 'email20@gmail.com',
                'no_hp' => '0831',
                'jabatan' => 'Analis Perkara Peradilan',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '20',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Muhammad Lutfi Khakim, A.Md.Kom.',
                'email' => 'email21@gmail.com',
                'no_hp' => '0832',
                'jabatan' => 'Dokumentalis Hukum',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '21',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Gilang Arief Maulana, S.E.',
                'email' => 'email22@gmail.com',
                'no_hp' => '0833',
                'jabatan' => 'Analis Pengelolaan Keuangan APBN Ahli Pertama',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '22',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Muhjar Nias Dani, S.Kom.',
                'email' => 'email23@gmail.com',
                'no_hp' => '0834',
                'jabatan' => 'Penata Kelola Sistem dan Teknologi Informasi',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '23',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Yudhis Salvania Pradana, S.I.Kom.',
                'email' => 'email24@gmail.com',
                'no_hp' => '0835',
                'jabatan' => 'Penata Keprotokolan',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '24',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Said Salasa',
                'email' => 'email25@gmail.com',
                'no_hp' => '0836',
                'jabatan' => 'Pengadministrasi Perkantoran',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '25',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Iksan Ohorella',
                'email' => 'email26@gmail.com',
                'no_hp' => '0837',
                'jabatan' => 'Operator Layanan Operasional',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '26',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Hamzah Syam',
                'email' => 'email27@gmail.com',
                'no_hp' => '0838',
                'jabatan' => 'Operator Layanan Operasional',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '27',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Yatino',
                'email' => 'email28@gmail.com',
                'no_hp' => '0839',
                'jabatan' => 'Operator Layanan Operasional',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '28',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Hari Supriyanto, S.T',
                'email' => 'email29@gmail.com',
                'no_hp' => '0840',
                'jabatan' => 'PPNPN',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '29',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Zilva Kurnia Aji, S.H',
                'email' => 'email30@gmail.com',
                'no_hp' => '0841',
                'jabatan' => 'PPNPN',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '30',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Ravid Bahar, S.H',
                'email' => 'email31@gmail.com',
                'no_hp' => '0842',
                'jabatan' => 'PPNPN',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '31',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Nur Komariah, S.Si',
                'email' => 'email32@gmail.com',
                'no_hp' => '0843',
                'jabatan' => 'PPNPN',
                'unit' => 'Pengadilan Tinggi Agama Papua Barat',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '32',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Samsudin Djaki, S.H., M.H.',
                'email' => 'email33@gmail.com',
                'no_hp' => '0844',
                'jabatan' => 'Ketua',
                'unit' => 'Pengadilan Agama Manokwari',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '33',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Sudarmin H.I.M. Tang, S.H.I.,M.H',
                'email' => 'email34@gmail.com',
                'no_hp' => '0845',
                'jabatan' => 'Wakil Ketua',
                'unit' => 'Pengadilan Agama Manokwari',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '34',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Khoirunnisa` Putri Kusumaningayu, S.H.',
                'email' => 'email35@gmail.com',
                'no_hp' => '0846',
                'jabatan' => 'Hakim',
                'unit' => 'Pengadilan Agama Manokwari',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '35',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Mohammad Abdul Kadir, S.Ag.',
                'email' => 'email36@gmail.com',
                'no_hp' => '0847',
                'jabatan' => 'Panitera',
                'unit' => 'Pengadilan Agama Manokwari',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '36',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Eddy Waluyo, S.E.',
                'email' => 'email37@gmail.com',
                'no_hp' => '0848',
                'jabatan' => 'Sekretaris',
                'unit' => 'Pengadilan Agama Manokwari',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '37',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Ummi Mahmudah, S.H.I.',
                'email' => 'email38@gmail.com',
                'no_hp' => '0849',
                'jabatan' => 'Panitera Muda Hukum',
                'unit' => 'Pengadilan Agama Manokwari',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '38',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Julinopianti Hutagaol, A. Mk',
                'email' => 'email39@gmail.com',
                'no_hp' => '0850',
                'jabatan' => 'Kepala Sub Bagian Kepegawaian, Organisasi, dan Tata Laksana',
                'unit' => 'Pengadilan Agama Manokwari',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '39',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Swartika Rahma Wulandari, S.H.',
                'email' => 'email40@gmail.com',
                'no_hp' => '0851',
                'jabatan' => 'Panitera Muda Gugatan',
                'unit' => 'Pengadilan Agama Manokwari',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '40',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Muh. Amirulhaq Nur Indarsyah, S.H.',
                'email' => 'email41@gmail.com',
                'no_hp' => '0852',
                'jabatan' => 'Juru Sita Pengganti',
                'unit' => 'Pengadilan Agama Manokwari',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '41',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Ilham Fathurrahman Dharmawan, S.H.',
                'email' => 'email42@gmail.com',
                'no_hp' => '0853',
                'jabatan' => 'Juru Sita Pengganti',
                'unit' => 'Pengadilan Agama Manokwari',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '42',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Septiandi Abbas, S.T.',
                'email' => 'email43@gmail.com',
                'no_hp' => '0854',
                'jabatan' => 'Pranata Komputer Pertama',
                'unit' => 'Pengadilan Agama Manokwari',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '43',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Ferdin Setiawan, A.Md.Kom.',
                'email' => 'email44@gmail.com',
                'no_hp' => '0855',
                'jabatan' => 'Dokumentalis Hukum',
                'unit' => 'Pengadilan Agama Manokwari',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '44',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Azhar Ghifari, A.Md.Kom.',
                'email' => 'email45@gmail.com',
                'no_hp' => '0856',
                'jabatan' => 'Dokumentalis Hukum',
                'unit' => 'Pengadilan Agama Manokwari',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '45',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Muh. Hidayat, S.T.',
                'email' => 'email46@gmail.com',
                'no_hp' => '0857',
                'jabatan' => 'Teknisi Sarana dan Prasarana',
                'unit' => 'Pengadilan Agama Manokwari',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '46',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Willian Muhamad Farhan, S.H.',
                'email' => 'email47@gmail.com',
                'no_hp' => '0858',
                'jabatan' => 'Analis Perkara Peradilan',
                'unit' => 'Pengadilan Agama Manokwari',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '47',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Dimas Majid Mahendra, A.Md.',
                'email' => 'email48@gmail.com',
                'no_hp' => '0859',
                'jabatan' => 'Dokumentalis Hukum',
                'unit' => 'Pengadilan Agama Manokwari',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '48',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Samuel Mafatihul Muqtadir, S.H.',
                'email' => 'email49@gmail.com',
                'no_hp' => '0860',
                'jabatan' => 'Analis Perkara Peradilan',
                'unit' => 'Pengadilan Agama Manokwari',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '49',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Siti Meriam Hamadi, S.H.I.',
                'email' => 'email50@gmail.com',
                'no_hp' => '0861',
                'jabatan' => 'Penata Layanan Operasional',
                'unit' => 'Pengadilan Agama Manokwari',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '50',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Mujriah, S.H.',
                'email' => 'email51@gmail.com',
                'no_hp' => '0862',
                'jabatan' => 'Penata Layanan Operasional',
                'unit' => 'Pengadilan Agama Manokwari',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '51',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Muh. Abdi Antasari, S.Si.',
                'email' => 'email52@gmail.com',
                'no_hp' => '0863',
                'jabatan' => 'Penata Layanan Operasional',
                'unit' => 'Pengadilan Agama Manokwari',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '52',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Eka Purnama Sari, S.K.M.',
                'email' => 'email53@gmail.com',
                'no_hp' => '0864',
                'jabatan' => 'Penata Layanan Operasional',
                'unit' => 'Pengadilan Agama Manokwari',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '53',
                'created_at' => null,
                'update_at' => null,
            ],
            [
                'id' => null,
                'name' => 'Muhammad Maulana Supandi',
                'email' => 'email54@gmail.com',
                'no_hp' => '0865',
                'jabatan' => 'Operator Layanan Operasional',
                'unit' => 'Pengadilan Agama Manokwari',
                'tingkatan' => null,
                'password' => 'passwordd',
                'role' => 'Peserta',
                'hirarki' => '54',
                'created_at' => null,
                'update_at' => null,
            ],
        ];

        // Determine which 'updated' column your table uses (update_at or updated_at)
        $timeKey = Schema::hasColumn('users', 'update_at') ? 'update_at' : 'updated_at';

        $rows = array_map(function($r) use ($timeKey) {
            // Normalize updated column
            if ($timeKey === 'updated_at') {
                if (isset($r['update_at']) && !isset($r['updated_at'])) {
                    $r['updated_at'] = $r['update_at'];
                }
                unset($r['update_at']);
            }

            // Fill timestamps if missing
            if (empty($r['created_at'])) {
                $r['created_at'] = now();
            }
            if (empty($r[$timeKey])) {
                $r[$timeKey] = now();
            }

            // Hash password if not already hashed
            $pass = $r['password'] ?? null;
            if (is_string($pass) && Str::startsWith($pass, ['$2y$', '$2b$', '$argon2id$', '$argon2i$'])) {
                // already hashed
            } else {
                $r['password'] = Hash::make($pass ?: Str::password(12));
            }

            return $r;
        }, $rawRows);

        // Insert using Query Builder (Laravel 7)
        DB::table('users')->insert($rows);
    }
}
